-- FOR THE CULTURE Editorial Engine
-- Run this once in the existing Galaxy Fire Supabase project's SQL Editor.

create table if not exists public.editorial_sources (
  id bigint generated by default as identity primary key,
  name text not null,
  feed_url text not null unique,
  site_url text not null,
  category text,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.editorial_stories (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_url text not null,
  original_url text not null,
  original_title text not null,
  original_excerpt text,
  original_published_at timestamptz,
  source_fingerprint text not null unique,
  relevance_score integer not null default 0,
  headline text not null,
  dek text,
  body text not null,
  category text not null default 'Culture',
  tags jsonb not null default '[]'::jsonb,
  slug text not null unique,
  status text not null default 'published' check (status in ('draft','review','published','archived')),
  auto_published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists editorial_stories_published_idx on public.editorial_stories (status, published_at desc);
create index if not exists editorial_stories_category_idx on public.editorial_stories (category);

insert into public.editorial_sources (name, feed_url, site_url, category) values
('The NATIVE', 'https://thenativemag.com/feed/', 'https://thenativemag.com/', 'Music & Culture'),
('The NATIVE Music', 'https://thenativemag.com/category/music/feed/', 'https://thenativemag.com/category/music/', 'Music'),
('PUNCH Entertainment', 'https://rss.punchng.com/v1/category/entertainment', 'https://punchng.com/topics/entertainment/', 'Entertainment'),
('PUNCH Interviews', 'https://rss.punchng.com/v1/category/interview', 'https://punchng.com/', 'Interviews'),
('The Guardian Nigeria — Arts', 'https://guardian.ng/category/art/?format=feed&type=rss', 'https://guardian.ng/category/art/', 'Art & Culture'),
('The Guardian Nigeria — Life', 'https://guardian.ng/category/life/?format=feed&type=rss', 'https://guardian.ng/category/life/', 'Culture & Lifestyle')
on conflict (feed_url) do update set enabled = true, name = excluded.name, site_url = excluded.site_url, category = excluded.category;

-- Keep this table server-side. The app uses the existing Galaxy Fire service-role connection.
